# Generated by Django 4.1.4 on 2023-01-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_Description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='POS/images/')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
