# Generated by Django 4.1.4 on 2023-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_System', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='POS_System/images/')),
            ],
        ),
    ]
