# Generated by Django 4.1.4 on 2023-01-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_System', '0003_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='logo_name',
            field=models.CharField(default='logo', max_length=10),
        ),
    ]
