# Generated by Django 4.1.4 on 2023-01-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS_System', '0004_logo_logo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
    ]
